#!/bin/bash
cd ..
ant
# for DEST in "ubuntu@54.200.142.79:/home/ubuntu"
for DEST in "root@54.200.63.206:/root"
do
  echo deploy to $DEST
  rsync -avz -e "ssh -i /home/lulu/my-first.pem" ./out/all/* $DEST/out
  rsync -avz -e "ssh -i /home/lulu/my-first.pem" ./all/* $DEST/all
done
cd all



# rsync -avz -e "ssh -i /home/lulu/my-first.pem" ubuntu@54.200.29.213:/home/ubuntu/all ~/.tmp/all777


# ubuntu@54.200.240.137:/home/ubuntu/u/


# SUSE Linux Enterprise Server 11 (i586)
# zypper install java-1_7*
# java version "1.7.0"
# Java(TM) SE Runtime Environment (build pxi3270sr5-20130619_01(SR5))
# IBM J9 VM (build 2.6, JRE 1.7.0 Linux x86-32 20130617_152572 (JIT enabled, AOT enabled)
# J9VM - R26_Java726_SR5_20130617_1436_B152572
# JIT  - r11.b04_20130528_38954ifx1
# GC   - R26_Java726_SR5_20130617_1436_B152572
# J9CL - 20130617_152572)
# JCL - 20130616_01 based on Oracle 7u25-b12
